spring:
  cloud:
    consul:
      host: consul
  kafka:
    bootstrap-servers: kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://65.2.171.207:8180/realms/healthcare/protocol/openid-connect/certs
