server:
  port: 8085
spring:
  application:
    name: notification-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://65.2.171.207:8180/realms/healthcare/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
