server.port=8084
spring.application.name=payment-service

spring.datasource.url=jdbc:postgresql://localhost:5435/paymentdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=payment-group

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/healthcare/protocol/openid-connect/certs
