server:
  port: 8087
spring:
  application:
    name: ai-symptom-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://65.2.171.207:8180/realms/healthcare/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
