server.port=8086
spring.application.name=telemedicine-service

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/healthcare/protocol/openid-connect/certs
