server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
          filters:
            - TokenRelay=
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/doctors/**
          filters:
            - TokenRelay=
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**
          filters:
            - TokenRelay=
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - TokenRelay=
        - id: telemedicine-service
          uri: lb://telemedicine-service
          predicates:
            - Path=/api/telemedicine/**
          filters:
            - TokenRelay=
        - id: ai-symptom-service
          uri: lb://ai-symptom-service
          predicates:
            - Path=/api/symptom-check/**
          filters:
            - TokenRelay=
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://65.2.171.207:8180/realms/healthcare/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://65.2.171.207:8180/realms/healthcare
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
