server.port=8088
spring.application.name=consultation-orchestrator

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true

spring.kafka.bootstrap-servers=localhost:9092

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/healthcare/protocol/openid-connect/certs
