server:
  port: 8081
spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/patientdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/healthcare/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
