spring:
  cloud:
    consul:
      host: consul
  datasource:
    url: jdbc:postgresql://postgres-payment:5432/paymentdb
  kafka:
    bootstrap-servers: kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/healthcare/protocol/openid-connect/certs
